# Generated by Django 5.0.7 on 2024-08-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gironalista',
            new_name='Giornalista',
        ),
    ]
